### ISSUE TITLE
Allow scroll on page with bee3d

### ISSUE THREAD

**Issue by mathishuettl** [lukeed/bee3d#38] opened 2016-11-30 09:13 UTC
Hello,

i have a simple web-application using bee3d slider.
When the App starts bee3d slider gets initialized but i have a button when i press it the view changes to a grid-view and i call slider.destroy(); but even when i do this i can't scroll.

When i remove bee3d from my project it's working fine so it hast to do something with the bee3d slider.

**Comment by lukeed** [comment] 2016-11-30 15:00
Hi there! This is a duplicate of #7, which I will tackle later this week.

I'm going to close this issue, but you may follow the linked copy for updates.

Thanks!

**Closed as completed by lukeed** 2016-11-30 15:00 UTC
Labels: duplicate
