### ISSUE TITLE
Coverflow effect when used as an image carousel the image is not clearly visible

### ISSUE THREAD

**Issue by sanjay17kol** [lukeed/bee3d#29] opened 2016-05-24 12:22 UTC
Having problem with :-
.bee3D--slide
 {
  -webkit-transition: opacity .7s ease, -webkit-transform 0.7s ease;
  transition: opacity .7s ease, transform 0.7s ease;
 }
the opacity and transform property

**Comment by lukeed** [comment] 2016-05-24 13:53
Hey there,

Make sure the `z-index` on `.bee3D--active` is greater than `10` -- 50 is probably a safe bet.

This won't fix the issue on Safari tho; that's a known Safari bug and I can't do anything about it 😢

**Comment by lukeed** [comment] 2016-07-15 05:08
Duplicate of #21

**Closed as completed by lukeed** 2016-07-15 05:08 UTC
Labels: bug, duplicate
